#include "UIManager.h"
#include "Player.h"
#include <sstream>
#include <iomanip>
UIManager::UIManager(){ font=nullptr; } void UIManager::setFont(sf::Font& f){ font=&f; }
sf::Text UIManager::text(unsigned size,const std::string& s,float x,float y,sf::Color c){ sf::Text t; t.setFont(*font); t.setCharacterSize(size); t.setString(s); t.setFillColor(c); t.setPosition(x,y); return t; }
void UIManager::card(sf::RenderWindow& w,const std::string& title,const std::string& value,float x,float y,float cw){ sf::RectangleShape r(sf::Vector2f(cw,48)); r.setPosition(x,y); r.setFillColor(sf::Color(250,248,240)); r.setOutlineThickness(2); r.setOutlineColor(sf::Color(40,40,40)); w.draw(r); w.draw(text(13,title,x+10,y+5,sf::Color(80,80,80))); sf::Text v=text(21,value,x+10,y+22); v.setStyle(sf::Text::Bold); w.draw(v); }
void UIManager::drawHUD(sf::RenderWindow& w,const Player& p,int wave,float waveTimer,float gameTime,const std::string& last){ float W=w.getSize().x,H=w.getSize().y,start=W/2.f-420.f,cw=130,g=12,y=12; std::ostringstream hp,mat,wv,tm,dmg,cd; hp<<p.getHp()<<"/"<<p.getMaxHp(); mat<<p.getMaterials(); wv<<wave; int sec=(int)gameTime%60; tm<<(int)(gameTime/60)<<":"<<(sec<10?"0":"")<<sec; dmg<<std::fixed<<std::setprecision(1)<<p.getDamage(); cd<<std::fixed<<std::setprecision(2)<<p.getCooldown(); card(w,"HP",hp.str(),start,y,cw); card(w,"MATERIALS",mat.str(),start+1*(cw+g),y,cw); card(w,"WAVE",wv.str(),start+2*(cw+g),y,cw); card(w,"TIME",tm.str(),start+3*(cw+g),y,cw); card(w,"DAMAGE",dmg.str(),start+4*(cw+g),y,cw); card(w,"COOLDOWN",cd.str(),start+5*(cw+g),y,cw); sf::RectangleShape back(sf::Vector2f(840,12)); back.setPosition(start,68); back.setFillColor(sf::Color(70,70,70)); w.draw(back); sf::RectangleShape bar(sf::Vector2f(840.f*((float)p.getHp()/p.getMaxHp()),12)); bar.setPosition(start,68); bar.setFillColor(sf::Color(215,55,55)); w.draw(bar); sf::RectangleShape bottom(sf::Vector2f(W-30,44)); bottom.setPosition(15,H-56); bottom.setFillColor(sf::Color(250,248,240)); bottom.setOutlineThickness(2); bottom.setOutlineColor(sf::Color(40,40,40)); w.draw(bottom); w.draw(text(21,"WASD / Arrows - Move",45,H-45)); w.draw(text(21,"Last upgrade: "+last,W/2.f-180,H-45,sf::Color(45,85,150))); w.draw(text(21,"ESC - Pause",W-200,H-45)); }
void UIManager::drawShop(sf::RenderWindow& w,const Player& p){ float W=w.getSize().x,H=w.getSize().y; sf::RectangleShape o(sf::Vector2f(W,H)); o.setFillColor(sf::Color(0,0,0,150)); w.draw(o); sf::RectangleShape b(sf::Vector2f(900,360)); b.setPosition(W/2-450,H/2-180); b.setFillColor(sf::Color(251,250,244)); b.setOutlineThickness(3); b.setOutlineColor(sf::Color(35,35,35)); w.draw(b); float x=b.getPosition().x+55,y=b.getPosition().y+25; w.draw(text(40,"Choose upgrade between waves",x+150,y)); std::ostringstream s1,s2,s3,s4; s1<<"1) Damage: "<<std::fixed<<std::setprecision(1)<<p.getDamage()<<" -> "<<p.getDamage()+0.5f; s2<<"2) Cooldown: "<<std::fixed<<std::setprecision(2)<<p.getCooldown()<<" -> "<<p.getCooldown()-0.04f; s3<<"3) Max HP: "<<p.getMaxHp()<<" -> "<<p.getMaxHp()+2<<" and heal +2"; s4<<"4) Move speed: "<<(int)p.getSpeed()<<" -> "<<(int)(p.getSpeed()+28); w.draw(text(29,s1.str(),x,y+85,sf::Color(230,170,50))); w.draw(text(29,s2.str(),x,y+135,sf::Color(80,170,210))); w.draw(text(29,s3.str(),x,y+185,sf::Color(230,90,120))); w.draw(text(29,s4.str(),x,y+235,sf::Color(70,180,90))); }
void UIManager::drawPause(sf::RenderWindow& w){ float W=w.getSize().x,H=w.getSize().y; sf::RectangleShape o(sf::Vector2f(W,H)); o.setFillColor(sf::Color(0,0,0,150)); w.draw(o); w.draw(text(54,"PAUSED",W/2-110,H*.35f,sf::Color::White)); w.draw(text(28,"Press ESC to continue",W/2-160,H*.45f,sf::Color::White)); }
void UIManager::drawGameOver(sf::RenderWindow& w,int wave,int mat){ float W=w.getSize().x,H=w.getSize().y; sf::RectangleShape o(sf::Vector2f(W,H)); o.setFillColor(sf::Color(0,0,0,170)); w.draw(o); std::ostringstream r; r<<"You survived "<<wave<<" waves and collected "<<mat<<" materials"; w.draw(text(58,"GAME OVER",W/2-175,H*.32f,sf::Color::White)); w.draw(text(28,r.str(),W/2-310,H*.43f,sf::Color::White)); w.draw(text(28,"Press R to restart",W/2-140,H*.51f,sf::Color::White)); }
